---
apiVersion: v1
kind: Namespace
metadata:
  name: mvn-pipeline

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: mvn-jenkins-deploy
  namespace: mvn-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - image: hemachandra1019/mvn-jenkins:<TAG>
        imagePullPolicy: Always
        name: myweb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: mvn-jenkins-svc
  namespace: mvn-pipeline
spec:
  ports:
  - nodePort: 32233
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myweb
  type: NodePort
